### ISSUE TITLE
Add SkySatScene & associated asset-types to CLI

### ISSUE THREAD

**Issue by tjmac** [samapriya/Clip-Ship-Planet-CLI#3]
`pclip: error: unrecognized arguments: --asst SkySatScene ortho_visual`

I would like to request the addition of SkySatScene as an item-type option as well as the associated asset-types. In particular ortho_visual & ortho_pansharpened for my use case. Thank you!

**Comment by samapriya** [comment]
Currently, the [Clips API does not support skysat](https://www.planet.com/docs/reference/clips-api/common-workflows/) and the tool should work once the API supports it this tool should be able to handle the request, looking forward to updates to Clips API

**Comment by samapriya** [comment]
This tool has now been tested with Skysat and seems to work as designed. Am hence closing this issue :)
