### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by ikesari** [samapriya/Clip-Ship-Planet-CLI#8]
I installed the latest version, on windows 10, successfully did the python setup.py install ..no error messages, but when I typed pclip -h to test.   I got error messages saying "NameError: name 'sys' is not defined" . What have I done wrong?

**Comment by samapriya** [comment]
Nothing wrong at your end , seems I had left out import sys in the main pclip.py file. I have fixed this in github and I will push the fix to pip soon. Download again and reinstall again and thanks for reporting

**Comment by ikesari** [comment]
Hello,

Thank you very much.  I have few questions.  I read your work writing ppipe
and pclip,   I was able to run ppipe but for some reasons the images were
not clipped, instead they were downloaded whole image.

Second, from pclip help, there is no function to filter based on cloud
cover and analytic_sr, while ppipe menu does have.  Can I put ppipe
argument in pclip ?  Thank you

Best regards,
Ike

**Comment by samapriya** [comment]
Hey Ike
ppipe is not designed for clipping operation so it does not clip

when you are creating your json file using
```pclip aoijson``` this is where you specify cloud cover and then use this to create the idlist
```
usage: pclip aoijson [-h] [--start START] [--end END] [--cloud CLOUD]
                     [--inputfile INPUTFILE] [--geo GEO] [--loc LOC]

optional arguments:
  -h, --help            show this help message and exit
  --start START         Start date in YYYY-MM-DD?
  --end END             End date in YYYY-MM-DD?
  --cloud CLOUD         Maximum Cloud Cover(0-1) representing 0-100
  --inputfile INPUTFILE
                        Choose a kml/shapefile/geojson or WKT file for
                        AOI(KML/SHP/GJSON/WKT) or WRS (6 digit RowPath
                        Example: 023042)
  --geo GEO             map.geojson/aoi.kml/aoi.shp/aoi.wkt file
  --loc LOC             Location where aoi.json file is to be stored
```
when you create idlist
```pclip idlist -h``` it takes into account cloud cover that you set up when structuring your json file
 ```
usage: pclip idlist [-h] [--aoi AOI] [--asset ASSET]

optional arguments:
  -h, --help     show this help message and exit
  --aoi AOI      Input path to the structured json file from which we will
                 generate the clips
  --asset ASSET  Choose from asset type for example:"PSOrthoTile
                 analytic"|"REOrthoTile analytic"
```
ppipe and pclip have two very different functions. Also note that the Clip & Ship API has been deprecated and will probably no longer work long term into the future for clipping.

Hope that helps,
Sam

**Comment by ikesari** [comment]
Dear Sam,

Thank you so much for your reply.  Oh I do hope the clip and ship still
works for the long run.  It is so helpful in saving the quota.  I check the
arguments from both pclip and ppipe.  Yes, ppipe does not clip but it can
filter the images that in the Planet saved search have been filtered images
only those covering 100% of the scene.  Is there any way to integrate this
feature to pclip?  Thank you.

Best regards,
Ike
